### ISSUE TITLE
Add a filter for `arrowKeys`

### ISSUE THREAD

**Issue by michaelbeil** [hyunsupul/aesop-core#246]
When chapters are present in a story pressing the arrow down on the keyboard scrolls down to the next chapter. We could add a filter to disable `arrowKeys: true`.

https://github.com/bearded-avenger/aesop-core/blob/c470aaedb414f3f2dda9f99b3095f3e41f041d96/public/includes/components/component-heading.php#L117

**Comment by michaelbeil** [comment]
Been playing around with a way to return up and down as false and right and left as true on scrollNav for timeline and chapter components:

``` jquery
if(e.which == 37, 39) {
	return true;
	},
elseif(e.which == 38, 40) {
	return false;
	},
```

Arrow keys have a number they are correlated with: `{left: 37, up: 38, right: 39, down: 40 };`

Should we just return this boolean false for now until we can have a better go at this @bearded-avenger?

**Comment by bearded-avenger** [comment]
https://github.com/bearded-avenger/aesop-core/blob/master/public/includes/components/component-heading.php#L117

**Comment by michaelbeil** [comment]
Yes, I reference that above. I am all ears.

**Comment by bearded-avenger** [comment]
my immediate thought is we'd have to modify the scrollnav script, which then makes it not stock. might cause issues.

**Comment by michaelbeil** [comment]
yea, as I was looking around it appeared to me like things could get hairy.

**Comment by phoenixenero** [comment]
Is this actually done or something? The part where you can disable the arrow keys I mean?

**Comment by hyunsupul** [comment]
The Chapter key navigation has have been changed from arrow keys to PgUp/PgDown. This change seems to satisfy some people. If a true filter capability is desired let me know.
