### ISSUE TITLE
Self video plays when reader is out of view

### ISSUE THREAD

**Issue by michaelbeil** [hyunsupul/aesop-core#297]
Replicated this locally, and have a video from a user on an issue with a video playing when out of view.  https://youtu.be/X5g-nzvqtTY

**Comment by CruiseMan** [comment]
When do you guys planning to fix ?

**Comment by michaelbeil** [comment]
There is no ETA currently.

**Comment by hyunsupul** [comment]
Hi the latest version 1.7.0 should fix this issue. By default the self video should play when in view and stop playing when outside view. You can change the behavior by changing the default options.
