### ISSUE TITLE
Aesop SE not working with Visual editor in WordPress 4.4 

### ISSUE THREAD

**Issue by brianrc** [hyunsupul/aesop-core#299]
When I try to re-edit a component after saving the post in 4.4, all the fields come up blank, not populated with previous entries.

I had to downgrade back to WordPress 4.3.1 in order for it to work again.

Tested with all other plugins disabled. 

What is going on?

**Comment by michaelbeil** [comment]
Fixed in https://github.com/hyunsupul/aesop-core/commit/51645e542577edfeabaf311e609e8f9ca1050bd1.
