### ISSUE TITLE
First Chapter Listed Twice

### ISSUE THREAD

**Issue by brianrc** [hyunsupul/aesop-core#302]
I can't figure out why this would be, but the first chapter is always listed twice in my theme.

![chapters](https://cloud.githubusercontent.com/assets/573939/12279688/9ab782e8-b956-11e5-866e-a056e240b1af.png)

I've noticed on other themes the first item is called "Top." 

Why might this be the case and how can I either hide it or change it to top?

**Comment by michaelbeil** [comment]
What theme are you using?

**Comment by brianrc** [comment]
It's a custom theme. I've tried disabling all plugins and even renaming the functions.php file with the no change.

Here is a live example.
http://thenextsystem.brianswebstudio.com/chapter-test/

**Comment by hyunsupul** [comment]
Hi the next version of ASE will most likely fix this.

**Comment by hyunsupul** [comment]
I plan to release the next version by early next week.

**Comment by brianrc** [comment]
So 1.6.10 - 1.6.11 broke the chapter menu completely. 1.6.12, brought it back, but now I don't have any chapters.

![chapters2](https://cloud.githubusercontent.com/assets/573939/12588824/7dbf59e0-c428-11e5-8820-8f51e1cd5b22.png)

**Comment by brianrc** [comment]
I guess my client updated the test version so you can see the issue here:
http://thenextsystem.brianswebstudio.com/chapter-test/

**Comment by brianrc** [comment]
This seems to be fixed with

```
add_filter('aesop_chapter_scroll_container', 'aesop_entry_content');
function aesop_entry_content() {
    return '.inner-info';
}
```

Thank you.
