### ISSUE TITLE
When editing a "content" block, an alert() pops up with the content....

### ISSUE THREAD

**Issue by khromov** [hyunsupul/aesop-core#303]
Aesop Story Engine 1.6.9, Novella theme.

See screenshot:
![screen shot 2016-01-15 at 12 28 30](https://cloud.githubusercontent.com/assets/1207507/12352148/ce00d6a2-bb83-11e5-8486-f1b7040aeebc.png)

**Comment by hyunsupul** [comment]
This should have been fixed with the latest release. (1.6.11)

**Comment by khromov** [comment]
@hyunsupul Great thanks, feel free to close this issue!
