### ISSUE TITLE
Aesop Styles removed

### ISSUE THREAD

**Issue by meanthemes** [hyunsupul/aesop-core#304]
Hey there, it looks as though at some point after 1.6.2 default Aesop styles have been removed, namely:

`<style id='ai-core-style-inline-css' type='text/css'>` etc. inline styles in the header.

We have two themes that rely on these styles, obviously we could add the styles back in via our own CSS but I wanted to understand the rationale for removing the default styles and wondered whether this could be on/off-able either via a Plugin setting or a hook (much like how you disable WooCommerce styles).

**Comment by hyunsupul** [comment]
Hi this change I believe was made by Nick Haskins who's no longer involved with the development. I will look into the issue and the history to get a better insight..

**Comment by hyunsupul** [comment]
Hi can i ask you a favor. I want to restore compatibility to your themes with our next version ASAP. Can I have an access to your themes so I can test them. Please write to me at hyunsupul@gmail.com

**Comment by meanthemes** [comment]
Lovely thank you, I've emailed them over to you.

**Comment by hyunsupul** [comment]
The issue has been addressed with the latest version of ASE
