### ISSUE TITLE
Timeline revealed only after scrolling to bottom

### ISSUE THREAD

**Issue by brianrc** [hyunsupul/aesop-core#305]
Noticing strange issue with the timeline only being revealed after scrolling to the very bottom of the page.

http://thenextsystem.dev/timeline-test/

Is that intended? Thanks.

**Comment by hyunsupul** [comment]
Hi the link doesn't seem to be valid now. It's not intended and Timeline bar should have position:fixed attribute so you don't have to scroll all the way to the bottom. Perhaps your theme has a style overriding it? If you have a link that works I can take a look at.

**Comment by hyunsupul** [comment]
Actually, if aesop_chapter_scroll_container() is not properly set you could have an issue like this. (like #302)

**Comment by brianrc** [comment]
Sorry, gave you the wrong URL and 'aesop_chapter_scroll_container' is set. You can see the issue here:
http://thenextsystem.brianswebstudio.com/timeline/

**Comment by hyunsupul** [comment]
Hi it looks like the issue is because .inner-info has z-index of 9, overriding the timeline bar's visibility. Either you can get rid of the z-index value of .inner-info or specify higher z-index for .aesop-timeline using custom css.

**Comment by brianrc** [comment]
Oh, wow. Good catch! Thank you.
