### ISSUE TITLE
Add "has-image" class to collection items

### ISSUE THREAD

**Issue by peiche** [hyunsupul/aesop-core#309]
It's impossible to style collection items differently, depending on whether or not they have a featured image. The <code>.aesop-collection-item-img</code> div is always present, and it would be ideal if there were a class added to the parent <code>.aesop-collection-item</code> element that indicates if an image is available or not.

**Comment by hyunsupul** [comment]
Sorry for long delay. But this change has been made. Now the the class aesop-has-image class is added.
