### ISSUE TITLE
jQuery.fn.live has been deprecated since jQuery 1.7 and *removed* since jQuery 1.9

### ISSUE THREAD

**Issue by boaf** [hyunsupul/aesop-core#310]
As the title says, `jQuery.fn.live` is no longer a valid function in recent versions of jQuery. The version of jQuery currently included with WordPress 4.4.2 appears to be 1.11.3.

Lines [public/assets/js/methods.js#L34](https://github.com/hyunsupul/aesop-core/blob/master/public/assets/js/methods.js#L34) and [public/assets/js/methods.js#L38](https://github.com/hyunsupul/aesop-core/blob/master/public/assets/js/methods.js#L38) both make use of `jQuery.fn.live`, which breaks in jQuery versions `>= 1.9`.

FWIW, the last time jQuery pre 1.9 was included in WordPress was sometime around WordPress 3.7.

I have forked aesop-core and applied a small modification (see boaf/aesop-core@53dc8511d724d0b69115fd5b0c2ffeaf3fcd8aa5) which I believe will fix this issue. If it's appropriate, I will create a PR.

**Comment by michaelbeil** [comment]
Have you tested this with all of the components and everything checks out? If so, a PR would be great.

**Comment by boaf** [comment]
Whoops, so sorry I didn't reply, @michaelbeil ! Not sure how I missed your comment.

I see the changes made it into 1.7.4, looks good!
