### ISSUE TITLE
Height is still important'd

### ISSUE THREAD

**Issue by peiche** [hyunsupul/aesop-core#312]
See [this line](https://github.com/hyunsupul/aesop-core/blob/866401ecc8bc073cc206b10d292a0ca8a349eb36/public/assets/css/ai-core.css#L492) in the compiled core css. I thought this was fixed in v1.7.4, but it's not. It's visible in [SVN](https://plugins.svn.wordpress.org/aesop-story-engine/tags/1.7.4/public/assets/css/ai-core.css) too.

**Comment by hyunsupul** [comment]
I fixed the css file. Thank you very much for pointing this out to me.
