### ISSUE TITLE
Broken Swipebox controls

### ISSUE THREAD

**Issue by peiche** [hyunsupul/aesop-core#315]
When clicking on an image to open the lightbox, the back/forward and close icons are missing. This is reproducible both in [my own theme](http://eichefam.net/2016/02/15/sharks-and-minnows/) and in the [Aesop Story Theme](http://eichefam.net/2016/02/15/sharks-and-minnows/?theme=aesop-story-theme-master).

Upon a little further investigation, I've found that the stylesheet is looking for this selector:
```
#swipebox-action #swipebox-prev,
#swipebox-action #swipebox-next,
#swipebox-action #swipebox-close
```

But there is currently no id of `swipebox-action` in the markup used by Swipebox. The markup was rewritten in [this commit](https://github.com/hyunsupul/aesop-core/commit/6b4e7159450f388a5703c3c4ab386b442a36a620) in `public/assets/js/swipebox.js`.

**Comment by hyunsupul** [comment]
I restored the javascript file. Thank you very much for pointing this out to me.
