### ISSUE TITLE
Undefined variable: hidden in component-gallery.php

### ISSUE THREAD

**Issue by peiche** [hyunsupul/aesop-core#321]
There is a problem with the latest version of ASE (1.9.6) when you have debug turned on:

```
Notice: Undefined variable: hidden in [...]\wp-content\plugins\aesop-story-engine\public\includes\components\component-gallery.php on line 61
```

You won't find it here in the repo because the file is different. The problem is that the `$hidden` variable is only defined inside an if block, but is referenced no matter what. If the variable is defined, say, to an empty string and then set inside the if block, then the problem will be resolved.

**Comment by peiche** [comment]
@hyunsupul the GitHub project has not seen an update since October 2016, yet the WordPress plugin just got updated. How should I submit bug fixes and feature requests?

**Comment by hyunsupul** [comment]
Hi Paul,
Sorry about slacking off on github. I had not been getting emails from github. I fixed this and the fix will go into the next release. Thank you for your support and faith even though I was not always responsive.  The best way to ensure you reach me would be to write me directly at hyunsupul at gmail  

Hyun
