### ISSUE TITLE
Video component bug

### ISSUE THREAD

**Issue by peiche** [hyunsupul/aesop-core#329]
In `ai-core.css`, there is this line:

```
.aesop-video-component .self .mejs-overlay-button {
  margin-top: 25% !important;
}
```

As far as I can tell, this doesn't do anything but break where the self-hosted video's large centered play button appears.

This is what it looks like with this line enabled (note the inspector highlighting):

![1499315021808screensave](https://user-images.githubusercontent.com/613931/27895620-8ed98d54-61d9-11e7-9b1e-796a41332f4b.png)

And this is what it looks like with this line removed:

![1499315284251screensave](https://user-images.githubusercontent.com/613931/27895629-a383d80e-61d9-11e7-998b-851d61dad84a.png)

Unless someone can tell me what specific use-case this line of CSS targets, I see no reason why it cannot be removed. (We should avoid using `!important` in any case, especially so that theme developers (_ahem_) don't have to enter an arms race of ever higher specificity and overrides.)

**Comment by hyunsupul** [comment]
Hi Paul, I am not sure about the reason that line was inserted. I will try to fix it in the next release.
