### ISSUE TITLE
Update Leaflet

### ISSUE THREAD

**Issue by peiche** [hyunsupul/aesop-core#330]
The third-party lib [Leaflet](https://github.com/Leaflet/Leaflet) is used in ASE, but it's old. Please update to the latest version.

The map component is currently broken on my theme [Cover2](https://github.com/peiche/cover2) due to Leaflet being outdated. I have interactive SVG icons in the header; each has a `<script>` tag inside, and this breaks Leaflet's script parser. This is fixed in the current version, however.

**Comment by hyunsupul** [comment]
I will try to update this week. Thank you for letting me know
