### ISSUE TITLE
Content Component produces malformatted HTML code using Gutenberg

### ISSUE THREAD

**Issue by reneneee** [hyunsupul/aesop-core#349]
The Content Component produces malformatted HTML code using Gutenberg and does not apply the color settings of text and background.

Configuration:
WordPress 5.0.3
Aesop Story Engine 2.0.7 (no other plugin activated)
Any Theme (use Twenty Nineteen 1.2 for example)

Steps to reproduce:

1. Create a new post
1. Add an Aesop Content Block
1. Add sample content e.g. `<h4>Test</h4>`
1. Click on Publish

The produced HTML source code is:

    <div                 class="aesop-component aesop-content-component   "
                    style="width:100%;max-width:100%;;">
    
                    <div id="aesop-content-component-859-1"
                         class="aesop-content-comp-wrap  " style=&quot;color:#FFFFFF;background-color:#222222;&quot;>
                        
                        <div class="aesop-component-content-data aesop-content-comp-inner " style=&quot;width:100%;max-width:100%;margin-left:auto;margin-right:auto;&quot;>
                            
                            <h4>Test Content</h4>
    
                        </div>                
                    </div>

The style is not applied due to the wrong escaping of quotation marks.

You can afterwards set the text color and background color, but the settings are not reflected in the produced HTML

**Comment by hyunsupul** [comment]
Hi thank you for letting me know this problem. It's fixed with 2.0.7.1
