### ISSUE TITLE
Gallery component creates empty error message in backend

### ISSUE THREAD

**Issue by cherbst** [hyunsupul/aesop-core#358]
Lines 525-538 in file [component-gallery.php](https://github.com/hyunsupul/aesop-core/blob/e80d418e1e888985053b54c33ff051d4d3dd4a3a/admin/includes/components/component-gallery.php#L525) create an empty error notice in the backend. It is not really clear what this is about and is confusing for users.

**Comment by AlchemyUnited** [comment]
@cherbst - To be clear, it's __not__ a PHP error, but a message / alert generated by Aesop, yes? And that you believe the message is ambiguous at best, and should be more helpful? Is that it? 

p.s. Thanks for the heads up.

**Comment by AlchemyUnited** [comment]
@hyunsupul - Perhaps this is something to generate on install? Or sooner (i.e., outside the actual component) in the process? I believe it might be possible to filter the components list and more the galleries. That is, let the plugin run, but effective remove anything that's not going to work well. Maybe/

**Comment by cherbst** [comment]
@AlchemyUnited - Yes, this is a notice generated by Aesop. And as the message is **empty** (there is nothing shown in the notice), yes it could be more helpful.

**Comment by hyunsupul** [comment]
This seems to be from way back when the gallery format changed many years ago. I think it's safe to remove this notice by now so I did.
